discord:
  chat-webhook-url: "https://discord.com"
  death:
    death-webhook-url: "https://discord.com"
    enable-images: false
    img-urls:
      default: ""
      drowning: ""
      lava: ""
      explosion: ""
      fall: ""
